### ISSUE TITLE
OpenGL Picking method

### ISSUE THREAD

**Issue by Zouch** [VORTEX-IRIT/Radium-Engine#18]
Ok, so we have some picking implemented. What is done actually is that we render a "picking texture" each frame, which basically holds a color id for each object in the seen.
When we do a picking request to the renderer, the picking texture is bound, and the whole texture buffer is copied locally, to read the pixel color at the requested position.

There are some problems with this method, which are 
* We are not thread safe, if the renderer is currently drawing and we do a picking request, the picking texture might be in an inconsistent state => we could call `glFinish()` before reading it.
* There is some memory overhead due to the fact that we are drawing a potentially useless texture on every frame => Maybe objects id could be usefull for other stuff ? 
* Doing a picking test requires loading the whole texture in a local buffer, which means potentially big buffer allocation and deletion plus the VRAM -> RAM transfer to just read one pixel

We could have another way of dealing with the picking, which would be a kind of "asynchronous" way.
We can ask the renderer to perform a picking request, at a given position. It basically just sets a flag to true, and records the picking position. Then, on the next render call, if the picking flag is set to true, we just do one more draw call to a picking frame buffer, and read the correct pixel.

Advantages : 
* There is one texture less to write for each draw call, which means less memory overhead, etc
* No allocation and VRAM -> RAM transfer for the whole texture when requesting the color of one pixel
* No object ID -> color stuff on every frame (which implies getting each drawable ID, etc...)
* Apparently thread safe (or with very little precautions)

Drawbacks :
* When some picking is requested, we need one more drawcall
* How to tell the guy who asked for some picking it has been done ?
* Picking request is delayed until the next render pass

**Comment by louen** [comment]
* Process events before rendering and add the pick query to the renderer ( so you get it at  the end of a frame).
